# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
orbs:
  node: circleci/node@4.1.0
  aws-cli: circleci/aws-cli@2.1.0
  aws-elastic-beanstalk: circleci/aws-elastic-beanstalk@2.0.1
  browser-tools: circleci/browser-tools@1.2.2
# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
jobs:
  deploy-api:
    docker:
      - image: cimg/base:stable
    steps:
      - node/install
      - checkout
      - aws-elastic-beanstalk/setup
      - run:
          name: "Udagram-api Install project dependecies"
          command: |
            npm run backend:install
      - run:
          name: "Udagram-api build"
          command: |
            npm run backend:build
      - run:
          name: "Udagram-api Deploying to Elastic beanstalk"
          command: |
            npm run backend:deploy
  deploy-frontend:
    docker:
      - image: cimg/base:stable
    steps:
      - node/install:
        node-version: '16.13'
      - browser-tools/install-chrome
      - checkout
      - aws-cli/setup:
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
          aws-region: AWS_DEFAULT_REGION
      - run:
          name: "Udagram-frontend install project dependecies"
          command: |
            npm run frontend:install
      - run:
          name: "Udagram-frontend run tests"
          command: |
            npm run frontend:test
      - run:
          name: "Udagram-frontend build"
          command: |
            npm run frontend:build
      - run:
          name: "Udagram-api Deploying to S3 bucket"
          command: |
            npm run frontend:deploy
workflows:
  deploy-full-project-workflow:
    jobs:
      - deploy-api:
        filters:
          branches:
            only: master
      - deploy-frontend:
        filters:
          branches:
            only: master